# Byte headers
HEADER_BYTES = 6
NUM_TXN         = b'NUM_TX'
CTP             = b'CTP_TX'
ERC             = b'ERC_TX'
CTP_SIGNAL      = b'CTP_SN'
ENERGY_TRANSFER = b'ENERGY'
END             = b'ENDXXX'
DELAY = 0